### ISSUE TITLE
Future of GNS-release branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/aaa#11]
What's the future of the `master` and `GNS-release` branches? Having `GNS-release` as the main branch is less convenient. 

a) Perhaps less disruptive option is to make it a default branch without any renaming: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch. @fingolfin do you think this will break ReleaseTools and GitHubPagesForGAP?

b) Renaming `master` to something else, and renaming `GNS-release` as `main` and making it default? 

c) Merging `GNS-release` back into `master`, accepting `GNS-release` versions in case of any conflicts? We can tag the revision of `master` prior to that, to have a clear indication of where they started to diverge?

In any case, it would be useful to rebase `GNS-release` to squash some commits - its early history is quite detailed and atomic, but most recent commits seems to intend as experiments to be rebased later.

**Comment by alex-konovalov** [comment]
I've noticed that @le27 renamed branches. I'm afraid that was a bit too rushed change. This may impact setup of other developers having clones or forks (@ssiccha, @james-d-mitchell, @ffloresbrito, @loeksnokes) who should be warned. 

It's also not (b) above, since in (b) I have suggested to have a new branch named `main`, not `master`. That might could have helped to avoid confusing Git: for example, otherwise my fork after your change now has old `master` and hence https://github.com/alex-konovalov/aaa/tree/master says "This branch is 37 commits ahead, 24 commits behind gap-packages:master.". 

I think the best way to resolve this would be for me to delete my fork and then create a new one when needed, and also to reset my local clone. Others may want to do the same too.

**Comment by le27** [comment]
I'm sorry for causing problems. I have now renamed the master branch (the branch originally called GNS-release) to main as in suggestion b) of @alex-konovalov's first comment.

**Comment by alex-konovalov** [comment]
Thanks @le27. I will reset my fork and local clone. I don't have any uncommitted or locally stored work, so that's not a problem for me.

**Comment by fingolfin** [comment]
ReleaseTools and GitHubPagesForGAP do not really care about branch names (perhaps with the exception of the `gh-pages` branch, in that the documentation mentions it but even that is only indirect, I think)
