### ISSUE TITLE
Fill in the abstract in PackageInfo.g

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/aaa#15]
This field is currently empty:
https://github.com/gap-packages/aaa/blob/3e8cfda77a454055dbb78303d21971cc15d67cdd/PackageInfo.g#L94

Please see a sample in https://github.com/gap-packages/example/blob/master/PackageInfo.g

**Comment by le27** [comment]
Thanks.

I have now filled in this field, see https://github.com/gap-packages/aaa/commit/2820d4d257194c2fda5c8ed4254294a71cd7bdc2

**Comment by alex-konovalov** [comment]
Thanks!
