### ISSUE TITLE
Clean up license details

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/aaa#16]
There are currently two files:
- `GPL` with GPL v3
- LICENSE with GPL v2

Whereas `PackageInfo.g` states GPL v2 or higher. You don't need both files, only GPL v2. You may look what some other GAP packages are doing (e.g. https://github.com/gap-packages/example).

**Comment by le27** [comment]
Thanks.

I have deleted the GPL file in favor of the LICENSE file.

**Comment by alex-konovalov** [comment]
Good!
