### ISSUE TITLE
'Transducer' clashes with "PatternClass" package

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/aaa#19]
It is not possible to load 'aaa' and 'PatternClass' at the same time, as they both define `Transducer`.

I don't know if the packages overlap in functionality. Worth an investigation to see if they are doing similar things or not.

**Comment by alex-konovalov** [comment]
Thanks. @le27 crucial to fix this if you will submit this for the redistribution with GAP.

**Comment by le27** [comment]
Thanks for this.
The transducers in PatternClass seem very similar to the ones in the aaa package. These are the main differences:

1. In aaa, the input and output alphabet of a transducer are always assumed to be "{0,1, \ldots, n-1}" for some n (not necessarily the same n for both).
2. In PatternClass, transducers have a set of terminal states.
3. In aaa, transducers are permitted to write words of any length upon reading a single letter.

In aaa terminology, a transducer as defined by Pattern Class appears to be equivalent to a synchronous transducer with a set of terminal states. If people want to be able to use both packages at some point, it seems not hard to write a function which converts between these types of transducers when possible. To resolve the name issue I plan to renam transducers as defined in aaa and autshift to "GNSTransducer" as these are transducers as they where defined in:

 R. I. Grigorchuk, V. V. Nekrashevich, and V. I. Sushchanskii. Automata, Dynamical
Systems, and Groups. Proceedings of the Steklov Institute of Mathematics, 231:128–203,
2000.
