### ISSUE TITLE
Welcome and what next: setup releases and website

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/aaa#6]
@le27 welcome to gap-packages. I've made you and @loeksnokes admins for this repository and allowed issues for this repository. Although, I'm still thinking whether the right way to to would be to migrate https://github.com/ffloresbrito/aaa instead - but on the other hand, as you say, all development is concentrated in your fork now, so perhaps could stay like that at least for now...

I've also updated tests of package development versions for their compatibility with the GAP development version (links at https://github.com/gap-system/gap-distribution) and they will run the default (i.e. specified in `PackageInfo.g` tests for aaa) in GAP's master, stable-4.11 and stable-4.10 branches.

As you see, they will use master branch of aaa - if you development mainly goes in another branch, please consider merging it when you can, making a release if you want to fix officially that version, and then proceed further. 

For publishing releases, and establishing and updating package webpages, we have automated tools by @fingolfin: https://github.com/gap-system/ReleaseTools and https://github.com/gap-system/GitHubPagesForGAP. I will be happy to help to set them up. With them, release procedure takes a couple of minutes, and you can easily release as often as needed.

There are several obvious changes with the package setup, but I see some already addressed at https://github.com/gap-packages/aaa/tree/GNS-release (e.g. codecov setup). So I will abstain from making any further suggestions for now.

**Comment by fingolfin** [comment]
I noticed that this package uses a nonstandard (for a GAP package) Travis/Codecov integration setup, i.e., not based on <https://github.com/gap-system/pkg-ci-scripts>. Any particular reason for that? It seems to have caused you quite some work (23 commits on scripts, .travis.yml and code-coverage-test-gap.py) with no obvious (to me, at least?) benefit. If there is something you are missing in the default Travis/Codecov integration, it'd be great to hear about it, too.

**Comment by alex-konovalov** [comment]
Maybe @le27 inherited setup from @james-d-mitchell's packages, but it's not me who can provide a qualified answer here...

**Comment by loeksnokes** [comment]
Hi all,

  This package has gone through renditions, but eventually it was under
Luke Elliot's direct control, so I am going to forward this on to him, as
he is more familiar with the package dependency hierarchy than myself: I
(with Shayo Olukoya) just created a lot of the algorithms that Fernando and
Luke coded up.

  I believe our main holdup at this point was that we did not have a good
manual, and that there was a verbal request by Dima Savchuk to get a good
description of what are in the three automata packages (his, Bartholdi's,
and ours) for users.  I will try to pick up the thread of this again this
week.

  Best Wishes,
  Collin

**Comment by alex-konovalov** [comment]
Some work to upgrade CI in PR #7, #8, #9. The manual seems to be almost ready. Would be useful to fix #10 before finishing the manual.

**Comment by fingolfin** [comment]
CI works now. The `PackageInfo.g` still references the old package location, though, and there is no package homepage yet.

**Comment by alex-konovalov** [comment]
Yes, this is in the plan.
